version: '3'

services: 
    postgresql:
        container_name: postgresql
        image: thuongnn1997/todo-app-db:latest
        volumes: 
            - /tmp/postgresdb:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root123
            - POSTGRES_DB=registry
        networks: 
            - todo-app

    golangfront:
        container_name: golangfront01
        image: thuongnn1997/todo-app:latest
        depends_on: 
            - postgresql
        ports: 
            - 8084:8080
        networks: 
            - todo-app

networks: 
    todo-app:
        driver: bridge
